apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: ceph-admin-secret-{{ .Release.Name }}
type: "kubernetes.io/rbd"
data:
  key: {{ .Values.ceph.adminKey | b64enc | quote }}
