apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rbd-provisioner-{{ .Release.Name }}
  labels:
{{ include "labels" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: rbd-provisioner
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: rbd-provisioner-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
