apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
{{ include "labels.core" . | indent 8 }}
    spec:
      serviceAccountName: rbd-provisioner
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: PROVISIONER_NAME
              value: ceph.com/rbd
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: tz-conf
              mountPath: /etc/localtime
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
      volumes:
        - name: tz-conf
          hostPath:
            path: /etc/localtime
